version: "3.3"

services:

  backend:
    container_name: "backend"
    image: jloperad/praxis-gildedrose_backend:latest
    ports:
      - 8081:8080
    environment:
      - DATABASE_HOST=group1-rds.cqqmj66dxtlw.us-east-1.rds.amazonaws.com
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres


  frontend:
    container_name: "frontend"
    image: jloperad/praxis-gildedrose_frontend:latest
    ports:
      - "4200:4200"
    environment:
      - BACKEND_HOST=backend
    depends_on:
      - backend