pipeline {
  agent any

  options {
    ansiColor('xterm')
  }
  stages{
    stage("Install dependencies") {
       steps {
            dir("API-tests"){
                sh 'npm ci'
                sh 'npm install mocha mochawesome cypress-mochawesome-reporter --save-dev'
            }
       }
    }
    stage("Test the UI") {
       steps {
            dir("API-tests"){
                sh 'npm test'
            }
       }
    }
  }
  post{
      always{
        publishHTML (
                    target : [
                        allowMissing: false,
                        alwaysLinkToLastBuild: true,
                        keepAll: true,
                        reportDir: '/var/lib/jenkins/workspace/API test pipeline/report/',
                        reportFiles: 'APIreport.html',
                        reportName: 'API-Tests Report'
                    ]
                )
      }
    }
}