pipeline {
  agent any
  stages{
    stage("Install dependencies") {
       steps {
            dir("API-tests"){
                sh 'npm ci'
            }
       }
    }
    stage("Test the UI") {
       steps {
            dir("API-tests"){
                sh 'npm test'
            }
       }
    }
  }
}