pipeline {
  agent any
  stages{
    stage("Install dependencies") {
       steps {
            dir("UI-Tests"){
                sh 'npm ci'
                sh "sudo -i"
                sh "apt-get install libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb"
            }
       }
    }
    stage("Test the UI") {
       steps {
            dir("UI-Tests"){
                sh 'npm test'
            }
       }
    }
  }
}