pipeline {
  agent any
  stages{
    stage("Install dependencies") {
       steps {
            dir("UI-Tests"){
                sh 'npm ci'
            }
       }
    }
    stage("Test the UI") {
       steps {
            dir("UI-Tests"){
                sh 'TERM=dumb'
                sh 'NO_COLOR=1 npm test'
            }
       }
    }
  }
}