pipeline {
  agent any
  stages{
    stage("Install dependencies") {
       steps {
          sh 'npm ci'
       }
    }
    stage("Test the UI") {
       steps {
          sh 'npm run test'
       }
    }
  }
}